// src/app/layout.tsx
import "./globals.css";
import { Metadata } from "next";
import ReduxProvider from './redux-provider';
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Navbar/>
          {children}
          <Footer/>
        </ReduxProvider>
      </body>
    </html>
  );
}
